name: ease_the_error
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.0.2
  toast: ^0.1.5

  provider: ^5.0.0
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  font_awesome_flutter: ^9.0.0
  webview_flutter: ^1.0.7
  carousel_pro: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img1.jpeg
    - assets/img2.jpeg
    - assets/img3.jpeg
    - assets/img4.jpeg
    - assets/img5.jpeg
    - assets/img6.jpeg
    - assets/img7.jpeg
    - assets/img8.jpeg
    - assets/achieve.jpeg
    - assets/b.jpg
    - assets/log.jpeg
    - assets/login.png
    - assets/emp1.jpeg
    - assets/emp2.jpeg
    - assets/emp3.jpeg
    - assets/al1.jpeg
    - assets/al2.jpeg
    - assets/al3.jpeg
    - assets/al4.jpeg
    - assets/al5.jpeg
    - assets/al6.jpeg
    - assets/emp5.jpeg
    - assets/act.jpeg
    - assets/emp.jpeg
    - assets/ac.jpeg
    - assets/academics.jpeg
    - assets/bus.jpeg
    - assets/canteen.jpeg
    - assets/library.jpeg
    - assets/placement.jpeg
    - assets/sa.jpeg
    - assets/rag.jpeg
    - assets/am.jpeg
    - assets/ap.jpeg
    - assets/auto.jpeg
    - assets/biotech.jpeg
    - assets/chem.jpeg
    - assets/civil.jpeg
    - assets/cs.jpeg
    - assets/ece.jpeg
    - assets/eee.jpeg
    - assets/hss.jpeg
    - assets/it.jpeg
    - assets/mar.jpeg
    - assets/mech.jpeg
    - assets/pl1.jpeg
    - assets/pl2.jpeg
    - assets/pl3.jpeg
    - assets/pl4.jpeg
    - assets/pl5.jpeg
    - assets/barg.jpeg
    - assets/graph.jpeg
    - assets/topc.jpeg
    - assets/lib1.jpeg
    - assets/lib2.jpeg
    - assets/lib3.jpeg
    - assets/lib4.jpeg
    - assets/sports.jpeg
    - assets/dispensary.jpeg
    - assets/can1.jpeg
    - assets/can2.jpg
    - assets/hostel.jpg
    - assets/research.jpg




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
