name: ease_the_error
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  bubble:
  intl:
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.0.2
  toast: ^0.1.5
  share: ^0.6.5+4
  curved_navigation_bar: ^0.4.0-nullsafety.0
  url_launcher: ^5.0.0
  provider: ^5.0.0
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  font_awesome_flutter: ^9.0.0
  webview_flutter: ^1.0.7
  carousel_pro: ^1.0.0
  google_fonts: ^2.1.0
  bottom_navy_bar: ^6.0.0
  flip_card: ^0.5.0
  page_transition: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/ambercard.png
    - assets/home_bg.png
    - assets/img1.jpeg
    - assets/img2.jpeg
    - assets/img3.jpeg
    - assets/img4.jpeg
    - assets/img5.jpeg
    - assets/img6.jpeg
    - assets/img7.jpeg
    - assets/img8.jpeg
    - assets/achieve.jpeg
    - assets/b.jpg
    - assets/log.jpeg
    - assets/login.png
    - assets/emp1.jpeg
    - assets/emp2.jpeg
    - assets/emp3.jpeg
    - assets/al1.jpg
    - assets/al2.jpg
    - assets/al3.jpg
    - assets/al4.jpg
    - assets/al5.jpg
    - assets/al6.jpg
    - assets/emp5.jpeg
    - assets/act.jpeg
    - assets/emp.jpeg
    - assets/ac.jpeg
    - assets/academics.jpeg
    - assets/bus.jpeg
    - assets/canteen.jpeg
    - assets/notes.jpg
    - assets/library.jpeg
    - assets/placement.jpeg
    - assets/sa.jpeg
    - assets/rag.jpeg
    - assets/am.jpeg
    - assets/ap.jpeg
    - assets/auto.jpeg
    - assets/biotech.jpeg
    - assets/chem.jpeg
    - assets/civil.jpeg
    - assets/cs.jpeg
    - assets/ece.jpeg
    - assets/eee.jpeg
    - assets/hss.jpeg
    - assets/it.jpeg
    - assets/mar.jpeg
    - assets/mech.jpeg
    - assets/pl1.jpeg
    - assets/pl2.jpeg
    - assets/pl3.jpeg
    - assets/pl4.jpeg
    - assets/pl5.jpeg
    - assets/barg.jpeg
    - assets/graph.jpeg
    - assets/topc.jpeg
    - assets/lib1.jpeg
    - assets/lib2.jpeg
    - assets/lib3.jpeg
    - assets/lib4.jpeg
    - assets/sports.jpeg
    - assets/dispensary.jpeg
    - assets/can1.jpeg
    - assets/can2.jpg
    - assets/hostel.jpg
    - assets/research.jpg
    - assets/barota.jpeg
    - assets/sambarrice.jpeg
    - assets/curdrice.jpeg
    - assets/papads.jpeg
    - assets/fullmeals.jpeg
    - assets/coffee.jfif
    - assets/tea.jfif
    - assets/frooti.jpeg
    - assets/appy.jpeg
    - assets/kavinsmilkshake.jpeg
    - assets/vada.jpeg
    - assets/noodles.jpeg
    - assets/svce.png
    - assets/bground.png
    - assets/bot.jpeg
    - assets/camera.png
    - assets/default.jpg
    - assets/bg.png
    - assets/dev.png
    - assets/wap.png
    - assets/welcome.png
    - assets/svce/activities.jpeg
    - assets/svce/chatbot.jpeg
    - assets/svce/erp.jpeg
    - assets/svce/home1.jpeg
    - assets/svce/login.jpeg
    - assets/svce/notes.jpeg
    - assets/svce/profile.jpeg
    - assets/svce/signup.jpeg
    - assets/welcome.gif
    - assets/activites_bg.png
    - assets/vada.png
    - assets/food_bg.png
    - assets/paytm.png
    - assets/gpay.png
    - assets/route/busparking.png
    - assets/route/carparking.png
    - assets/route/cricketground.png
    - assets/route/ground.png
    - assets/route/hostel.png
    - assets/route/ccd.png
    - assets/route/library.png
    - assets/route/temple.png
    - assets/route/swimmingpool.png
    - assets/route/block.png

    - assets/route/auto.png
    - assets/route/biotech.png
    - assets/route/chem.png

    - assets/route/oat.jpg

    - assets/route/substation.png
    - assets/route/pond.png
    - assets/route/chillout.png

    - assets/route/mph.png
    - assets/vegpuff.png
    - assets/paneerpuff.png
    - assets/mushroompuffs.png
    - assets/samosa.png
    - assets/kadaipaneerwraproll.png
    - assets/chocodoughnut.png
    - assets/walnutbrownie.png
    - assets/walnutbrowniewithicecream.png
    - assets/kesarpistakulfi.png
    - assets/matkakulfi.png
    - assets/pineapplecreambun.png
    - assets/strawberrycreambun.png
    - assets/paneertikkasandwich.png
    - assets/cheesesandwich.png
    - assets/blackforestpastry.png
    - assets/vanillapastry.png
    - assets/pineapplepastry.png
    - assets/strawberrypastry.png
    - assets/blueberrypastry.png
    - assets/chocofantasy.png
    - assets/lemonsoda.png
    - assets/cola.png
    - assets/blueberrysoda.png
    - assets/orangesoda.png
    - assets/fruitale.png
    - assets/kalakata.png
    - assets/jaljeera.png
    - assets/mangosoda.png
    - assets/strawberrysoda.png
    - assets/hotchillsoda.png
    - assets/chocolateshake.png
    - assets/mangoshake.png
    - assets/strawberryshake.png
    - assets/vanillashake.png
    - assets/blackcurrantshake.png
    - assets/pineapplecrusher.png
    - assets/strawberrycrusher.png
    - assets/lycheecrusher.png
    - assets/kiwicrusher.png
    - assets/blackcurrantshake.png
    - assets/orangecrusher.png
    - assets/coldcoffeecrusher.png
    - assets/chocolatecrusher.png
    - assets/kesarelaichicrusher.png
    - assets/butterscotchcrusher.png
    - assets/figcrusher.png
    - assets/alphonsocrusher.png
    - assets/espresso.png
    - assets/americano.png
    - assets/cappucino.png
    - assets/cafelatte.png
    - assets/cafemocha.png
    - assets/vanillacuppucino.png
    - assets/garamchai.png
    - assets/masalchai.png
    - assets/gingerchai.png
    - assets/hotlemonchai.png
    - assets/cardamomchai.png
    - assets/horlicks.png
    - assets/boost.png
    - assets/badammilk.png
    - assets/eskimocoffee.png
    - assets/tropicalmoksha.png
    - assets/lemonicetea.png
    - assets/flavoredchocolatemoksha.png
    - assets/flavoredcoldchoco.png
    - assets/orangillo.png
    - assets/guavafreeze.png
    - assets/chococookieslush.png
    - assets/jaljeeraslush.png
    - assets/freshlemonslush.png
    - assets/creamytomatosoup.png
    - assets/sweetcornsoup.png
    - assets/tomyumsoup.png

    - assets/pongal.png
    - assets/vada.png
    - assets/idly.png
    - assets/poori.png
    - assets/dosa.png
    - assets/meals.png
    - assets/sambarrice.png
    - assets/brinjirice.png
    - assets/friedrice.png
    - assets/tomatorice.png
    - assets/coconutrice.png
    - assets/puthinarice.png
    - assets/corianderrice.png
    - assets/curdrice.png
    - assets/cholapoori.png
    - assets/chappathi.png
    - assets/parotta.png
    - assets/bonda.png
    - assets/bajji.png
    - assets/masalvada.png
    - assets/miniidlysambar.png
    - assets/sambarvada.png

    - assets/karasev.png
    - assets/kaarabhoodi.png
    - assets/vegroll.png
    - assets/samosa.png
    - assets/vegpuff.png
    - assets/tea.png
    - assets/coffee.png
    - assets/hotmilk.png
    - assets/dairymilk.png
    - assets/fivestar.png
    - assets/perk.png


    - assets/snickers.png
    - assets/parle.png
    - assets/parlechocopie.png
    - assets/oreo.png
    - assets/hideandseek.png
    - assets/parlemilano.png
    - assets/milkbikis.png
    - assets/mariegold.png
    - assets/5050.png
    - assets/treat.png
    - assets/goodday.png
    - assets/bourbon.png
    - assets/britaniacake.png
    - assets/jimjam.png
    - assets/cornpuffs.png
    - assets/lays.png
    - assets/appy.png
    - assets/frootis.png
    - assets/appyfizz.png
    - assets/frooti.png
    - assets/cubacafe.png
    - assets/tropicana.png
    - assets/milkshake.png
    - assets/zerocoke.png
    - assets/thumbsup.png
    - assets/tincoke.png
    - assets/sprite.png
    - assets/pulpyorange.png
    - assets/mineralwater.png








  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
